# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Computer_Graphics_Work\Simple2D\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 676)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = DrawWidget(self.centralWidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 0, 771, 571))
        self.widget.setMouseTracking(True)
        self.widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 869, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_F = QtWidgets.QMenu(self.menuBar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menuBar)
        self.menu_E.setObjectName("menu_E")
        self.menu_V = QtWidgets.QMenu(self.menuBar)
        self.menu_V.setObjectName("menu_V")
        self.menu_I = QtWidgets.QMenu(self.menuBar)
        self.menu_I.setObjectName("menu_I")
        self.menu_M = QtWidgets.QMenu(self.menuBar)
        self.menu_M.setObjectName("menu_M")
        self.menu_T = QtWidgets.QMenu(self.menu_M)
        self.menu_T.setObjectName("menu_T")
        self.menu_C = QtWidgets.QMenu(self.menu_M)
        self.menu_C.setGeometry(QtCore.QRect(650, 195, 161, 237))
        self.menu_C.setObjectName("menu_C")
        self.menu_O = QtWidgets.QMenu(self.menu_M)
        self.menu_O.setObjectName("menu_O")
        self.menu_W = QtWidgets.QMenu(self.menuBar)
        self.menu_W.setObjectName("menu_W")
        self.menu_H = QtWidgets.QMenu(self.menuBar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(90, 585))
        self.dockWidget_3.setMaximumSize(QtCore.QSize(90, 585))
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.Button_selsct = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_selsct.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.Button_selsct.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/2x_cursor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_selsct.setIcon(icon)
        self.Button_selsct.setIconSize(QtCore.QSize(45, 45))
        self.Button_selsct.setCheckable(True)
        self.Button_selsct.setChecked(False)
        self.Button_selsct.setObjectName("Button_selsct")
        self.Button_adjust = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_adjust.setGeometry(QtCore.QRect(45, 0, 45, 45))
        self.Button_adjust.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/cursorcurse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_adjust.setIcon(icon1)
        self.Button_adjust.setIconSize(QtCore.QSize(45, 45))
        self.Button_adjust.setCheckable(True)
        self.Button_adjust.setObjectName("Button_adjust")
        self.Button_line = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_line.setGeometry(QtCore.QRect(0, 45, 45, 45))
        self.Button_line.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_line.setIcon(icon2)
        self.Button_line.setIconSize(QtCore.QSize(45, 45))
        self.Button_line.setCheckable(True)
        self.Button_line.setObjectName("Button_line")
        self.Button_polyline = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_polyline.setGeometry(QtCore.QRect(45, 45, 45, 45))
        self.Button_polyline.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/polyline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_polyline.setIcon(icon3)
        self.Button_polyline.setIconSize(QtCore.QSize(45, 45))
        self.Button_polyline.setCheckable(True)
        self.Button_polyline.setObjectName("Button_polyline")
        self.Button_rect = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_rect.setGeometry(QtCore.QRect(0, 90, 45, 45))
        self.Button_rect.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/2x_after effects-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_rect.setIcon(icon4)
        self.Button_rect.setIconSize(QtCore.QSize(45, 45))
        self.Button_rect.setCheckable(True)
        self.Button_rect.setObjectName("Button_rect")
        self.Button_ellipse = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_ellipse.setGeometry(QtCore.QRect(45, 90, 45, 45))
        self.Button_ellipse.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/2x_ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_ellipse.setIcon(icon5)
        self.Button_ellipse.setIconSize(QtCore.QSize(45, 45))
        self.Button_ellipse.setCheckable(True)
        self.Button_ellipse.setObjectName("Button_ellipse")
        self.Button_curse = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_curse.setGeometry(QtCore.QRect(0, 135, 45, 45))
        self.Button_curse.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/curse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_curse.setIcon(icon6)
        self.Button_curse.setIconSize(QtCore.QSize(45, 45))
        self.Button_curse.setCheckable(True)
        self.Button_curse.setObjectName("Button_curse")
        self.Button_polygon = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_polygon.setGeometry(QtCore.QRect(45, 135, 45, 45))
        self.Button_polygon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/polygon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_polygon.setIcon(icon7)
        self.Button_polygon.setIconSize(QtCore.QSize(45, 45))
        self.Button_polygon.setCheckable(True)
        self.Button_polygon.setObjectName("Button_polygon")
        self.Button_lnk = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_lnk.setGeometry(QtCore.QRect(0, 180, 45, 45))
        self.Button_lnk.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/2x_ink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_lnk.setIcon(icon8)
        self.Button_lnk.setIconSize(QtCore.QSize(45, 45))
        self.Button_lnk.setCheckable(True)
        self.Button_lnk.setObjectName("Button_lnk")
        self.Button_pot = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_pot.setGeometry(QtCore.QRect(45, 180, 45, 45))
        self.Button_pot.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/2x_paint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_pot.setIcon(icon9)
        self.Button_pot.setIconSize(QtCore.QSize(45, 45))
        self.Button_pot.setCheckable(True)
        self.Button_pot.setObjectName("Button_pot")
        self.Button_straw = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_straw.setGeometry(QtCore.QRect(0, 225, 45, 45))
        self.Button_straw.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/2x_eyedroper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_straw.setIcon(icon10)
        self.Button_straw.setIconSize(QtCore.QSize(45, 45))
        self.Button_straw.setCheckable(True)
        self.Button_straw.setObjectName("Button_straw")
        self.Button_lnkcolor = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_lnkcolor.setGeometry(QtCore.QRect(45, 270, 45, 45))
        self.Button_lnkcolor.setText("")
        self.Button_lnkcolor.setIconSize(QtCore.QSize(40, 40))
        self.Button_lnkcolor.setObjectName("Button_lnkcolor")
        self.Button_showlnk = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_showlnk.setEnabled(False)
        self.Button_showlnk.setGeometry(QtCore.QRect(0, 270, 45, 45))
        self.Button_showlnk.setText("")
        self.Button_showlnk.setIcon(icon8)
        self.Button_showlnk.setIconSize(QtCore.QSize(45, 45))
        self.Button_showlnk.setCheckable(True)
        self.Button_showlnk.setObjectName("Button_showlnk")
        self.Button_showpot = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_showpot.setEnabled(False)
        self.Button_showpot.setGeometry(QtCore.QRect(0, 315, 45, 45))
        self.Button_showpot.setText("")
        self.Button_showpot.setIcon(icon9)
        self.Button_showpot.setIconSize(QtCore.QSize(45, 45))
        self.Button_showpot.setCheckable(True)
        self.Button_showpot.setObjectName("Button_showpot")
        self.Button_potcolor = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_potcolor.setGeometry(QtCore.QRect(45, 315, 45, 45))
        self.Button_potcolor.setText("")
        self.Button_potcolor.setIconSize(QtCore.QSize(40, 40))
        self.Button_potcolor.setObjectName("Button_potcolor")
        self.Button_defaultcolor = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_defaultcolor.setGeometry(QtCore.QRect(0, 360, 45, 45))
        self.Button_defaultcolor.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_defaultcolor.setIcon(icon11)
        self.Button_defaultcolor.setIconSize(QtCore.QSize(45, 45))
        self.Button_defaultcolor.setCheckable(True)
        self.Button_defaultcolor.setObjectName("Button_defaultcolor")
        self.Button_nocolor = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_nocolor.setEnabled(True)
        self.Button_nocolor.setGeometry(QtCore.QRect(45, 360, 45, 45))
        self.Button_nocolor.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/nocolor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_nocolor.setIcon(icon12)
        self.Button_nocolor.setIconSize(QtCore.QSize(45, 45))
        self.Button_nocolor.setCheckable(True)
        self.Button_nocolor.setObjectName("Button_nocolor")
        self.Button_scale = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_scale.setEnabled(False)
        self.Button_scale.setGeometry(QtCore.QRect(0, 405, 45, 45))
        self.Button_scale.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/scale.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_scale.setIcon(icon13)
        self.Button_scale.setIconSize(QtCore.QSize(45, 45))
        self.Button_scale.setCheckable(True)
        self.Button_scale.setObjectName("Button_scale")
        self.Button_rotate = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_rotate.setEnabled(False)
        self.Button_rotate.setGeometry(QtCore.QRect(45, 405, 45, 45))
        self.Button_rotate.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/2x_left-rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_rotate.setIcon(icon14)
        self.Button_rotate.setIconSize(QtCore.QSize(45, 45))
        self.Button_rotate.setCheckable(True)
        self.Button_rotate.setObjectName("Button_rotate")
        self.Button_none = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.Button_none.setEnabled(False)
        self.Button_none.setGeometry(QtCore.QRect(45, 225, 45, 45))
        self.Button_none.setText("")
        self.Button_none.setIconSize(QtCore.QSize(45, 45))
        self.Button_none.setObjectName("Button_none")
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.action_newfile = QtWidgets.QAction(MainWindow)
        self.action_newfile.setCheckable(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/2x_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_newfile.setIcon(icon15)
        self.action_newfile.setObjectName("action_newfile")
        self.action_open = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/2x_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon16)
        self.action_open.setObjectName("action_open")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_save = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon17)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_print = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/2x_printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_print.setIcon(icon18)
        self.action_print.setObjectName("action_print")
        self.action_print_preview = QtWidgets.QAction(MainWindow)
        self.action_print_preview.setObjectName("action_print_preview")
        self.action_print_set = QtWidgets.QAction(MainWindow)
        self.action_print_set.setObjectName("action_print_set")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_revoke = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/2x_reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_revoke.setIcon(icon19)
        self.action_revoke.setObjectName("action_revoke")
        self.action_recovery = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icon/2x_anti-reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_recovery.setIcon(icon20)
        self.action_recovery.setObjectName("action_recovery")
        self.action_shear = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icon/2x_scissor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_shear.setIcon(icon21)
        self.action_shear.setObjectName("action_shear")
        self.action_copy = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icon/2x_file-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon22)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icon/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon23)
        self.action_paste.setObjectName("action_paste")
        self.action_delete = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icon/x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete.setIcon(icon24)
        self.action_delete.setObjectName("action_delete")
        self.action_toolbar = QtWidgets.QAction(MainWindow)
        self.action_toolbar.setCheckable(True)
        self.action_toolbar.setChecked(True)
        self.action_toolbar.setEnabled(True)
        self.action_toolbar.setVisible(True)
        self.action_toolbar.setObjectName("action_toolbar")
        self.action_statubar = QtWidgets.QAction(MainWindow)
        self.action_statubar.setCheckable(True)
        self.action_statubar.setChecked(True)
        self.action_statubar.setObjectName("action_statubar")
        self.action_toolbox = QtWidgets.QAction(MainWindow)
        self.action_toolbox.setCheckable(True)
        self.action_toolbox.setObjectName("action_toolbox")
        self.action_attribute_panel = QtWidgets.QAction(MainWindow)
        self.action_attribute_panel.setObjectName("action_attribute_panel")
        self.action_line = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icon/22"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_line.setIcon(icon25)
        self.action_line.setObjectName("action_line")
        self.action_broken_line = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icon/24"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_broken_line.setIcon(icon26)
        self.action_broken_line.setObjectName("action_broken_line")
        self.action_rect = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icon/4"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rect.setIcon(icon27)
        self.action_rect.setObjectName("action_rect")
        self.action_ellipse = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icon/7"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ellipse.setIcon(icon28)
        self.action_ellipse.setObjectName("action_ellipse")
        self.action_curve = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icon/18"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_curve.setIcon(icon29)
        self.action_curve.setObjectName("action_curve")
        self.action_polygon = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icon/23"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_polygon.setIcon(icon30)
        self.action_polygon.setObjectName("action_polygon")
        self.action_select = QtWidgets.QAction(MainWindow)
        self.action_select.setCheckable(True)
        self.action_select.setChecked(False)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icon/6"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select.setIcon(icon31)
        self.action_select.setObjectName("action_select")
        self.action_adjust = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icon/19"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_adjust.setIcon(icon32)
        self.action_adjust.setObjectName("action_adjust")
        self.action_scale = QtWidgets.QAction(MainWindow)
        self.action_scale.setObjectName("action_scale")
        self.action_rotate = QtWidgets.QAction(MainWindow)
        self.action_rotate.setObjectName("action_rotate")
        self.action_90_clockwise = QtWidgets.QAction(MainWindow)
        self.action_90_clockwise.setObjectName("action_90_clockwise")
        self.action_90_anti_clockwise = QtWidgets.QAction(MainWindow)
        self.action_90_anti_clockwise.setObjectName("action_90_anti_clockwise")
        self.action_180rotate = QtWidgets.QAction(MainWindow)
        self.action_180rotate.setObjectName("action_180rotate")
        self.action_horizontal_flip = QtWidgets.QAction(MainWindow)
        self.action_horizontal_flip.setObjectName("action_horizontal_flip")
        self.action_vertical_flip = QtWidgets.QAction(MainWindow)
        self.action_vertical_flip.setObjectName("action_vertical_flip")
        self.action_ink_bottle = QtWidgets.QAction(MainWindow)
        self.action_ink_bottle.setCheckable(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icon/12"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ink_bottle.setIcon(icon33)
        self.action_ink_bottle.setObjectName("action_ink_bottle")
        self.action_paint_pot = QtWidgets.QAction(MainWindow)
        self.action_paint_pot.setCheckable(True)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icon/14"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paint_pot.setIcon(icon34)
        self.action_paint_pot.setObjectName("action_paint_pot")
        self.action_straw = QtWidgets.QAction(MainWindow)
        self.action_straw.setCheckable(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icon/8"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_straw.setIcon(icon35)
        self.action_straw.setObjectName("action_straw")
        self.action_depict_color = QtWidgets.QAction(MainWindow)
        self.action_depict_color.setObjectName("action_depict_color")
        self.action_fill_color = QtWidgets.QAction(MainWindow)
        self.action_fill_color.setObjectName("action_fill_color")
        self.action_default_color = QtWidgets.QAction(MainWindow)
        self.action_default_color.setObjectName("action_default_color")
        self.action_no_color = QtWidgets.QAction(MainWindow)
        self.action_no_color.setObjectName("action_no_color")
        self.action_move_top = QtWidgets.QAction(MainWindow)
        self.action_move_top.setObjectName("action_move_top")
        self.action_move_up = QtWidgets.QAction(MainWindow)
        self.action_move_up.setObjectName("action_move_up")
        self.action_move_down = QtWidgets.QAction(MainWindow)
        self.action_move_down.setObjectName("action_move_down")
        self.action_move_bottom = QtWidgets.QAction(MainWindow)
        self.action_move_bottom.setObjectName("action_move_bottom")
        self.action_use = QtWidgets.QAction(MainWindow)
        self.action_use.setObjectName("action_use")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_out_image = QtWidgets.QAction(MainWindow)
        self.action_out_image.setObjectName("action_out_image")
        self.menu_F.addAction(self.action_newfile)
        self.menu_F.addAction(self.action_open)
        self.menu_F.addAction(self.action_close)
        self.menu_F.addAction(self.action_save)
        self.menu_F.addAction(self.action_save_as)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_out_image)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_print)
        self.menu_F.addAction(self.action_print_preview)
        self.menu_F.addAction(self.action_print_set)
        self.menu_F.addSeparator()
        self.menu_F.addSeparator()
        self.menu_E.addAction(self.action_revoke)
        self.menu_E.addAction(self.action_recovery)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_shear)
        self.menu_E.addAction(self.action_copy)
        self.menu_E.addAction(self.action_paste)
        self.menu_E.addAction(self.action_delete)
        self.menu_V.addAction(self.action_toolbar)
        self.menu_V.addAction(self.action_statubar)
        self.menu_V.addSeparator()
        self.menu_V.addAction(self.action_toolbox)
        self.menu_V.addAction(self.action_attribute_panel)
        self.menu_I.addAction(self.action_line)
        self.menu_I.addAction(self.action_broken_line)
        self.menu_I.addAction(self.action_rect)
        self.menu_I.addAction(self.action_ellipse)
        self.menu_I.addAction(self.action_curve)
        self.menu_I.addAction(self.action_polygon)
        self.menu_T.addAction(self.action_scale)
        self.menu_T.addAction(self.action_rotate)
        self.menu_T.addSeparator()
        self.menu_T.addAction(self.action_90_clockwise)
        self.menu_T.addAction(self.action_90_anti_clockwise)
        self.menu_T.addAction(self.action_180rotate)
        self.menu_T.addSeparator()
        self.menu_T.addAction(self.action_horizontal_flip)
        self.menu_T.addAction(self.action_vertical_flip)
        self.menu_C.addAction(self.action_ink_bottle)
        self.menu_C.addAction(self.action_paint_pot)
        self.menu_C.addAction(self.action_straw)
        self.menu_C.addSeparator()
        self.menu_C.addAction(self.action_depict_color)
        self.menu_C.addAction(self.action_fill_color)
        self.menu_C.addAction(self.action_default_color)
        self.menu_C.addAction(self.action_no_color)
        self.menu_O.addAction(self.action_move_top)
        self.menu_O.addAction(self.action_move_up)
        self.menu_O.addAction(self.action_move_down)
        self.menu_O.addAction(self.action_move_bottom)
        self.menu_M.addAction(self.action_select)
        self.menu_M.addAction(self.action_adjust)
        self.menu_M.addAction(self.menu_T.menuAction())
        self.menu_M.addAction(self.menu_C.menuAction())
        self.menu_M.addSeparator()
        self.menu_M.addAction(self.menu_O.menuAction())
        self.menu_H.addAction(self.action_use)
        self.menu_H.addAction(self.action_about)
        self.menuBar.addAction(self.menu_F.menuAction())
        self.menuBar.addAction(self.menu_E.menuAction())
        self.menuBar.addAction(self.menu_V.menuAction())
        self.menuBar.addAction(self.menu_I.menuAction())
        self.menuBar.addAction(self.menu_M.menuAction())
        self.menuBar.addAction(self.menu_W.menuAction())
        self.menuBar.addAction(self.menu_H.menuAction())
        self.toolBar.addAction(self.action_newfile)
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_revoke)
        self.toolBar.addAction(self.action_recovery)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_shear)
        self.toolBar.addAction(self.action_copy)
        self.toolBar.addAction(self.action_paste)
        self.toolBar.addAction(self.action_delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_print)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_V.setTitle(_translate("MainWindow", "查看(&V)"))
        self.menu_I.setTitle(_translate("MainWindow", "图形(&I)"))
        self.menu_M.setTitle(_translate("MainWindow", "修改(&M)"))
        self.menu_T.setTitle(_translate("MainWindow", "转换(&T)"))
        self.menu_C.setTitle(_translate("MainWindow", "颜色(&C)"))
        self.menu_O.setTitle(_translate("MainWindow", "排序(&O)"))
        self.menu_W.setTitle(_translate("MainWindow", "窗口(&W)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(&H)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "工具箱"))
        self.action_newfile.setText(_translate("MainWindow", "新建(&N)      "))
        self.action_newfile.setToolTip(_translate("MainWindow", "新建(N)"))
        self.action_newfile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open.setText(_translate("MainWindow", "打开(&O)… "))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_close.setText(_translate("MainWindow", "关闭(&C)"))
        self.action_save.setText(_translate("MainWindow", "保存(&S)"))
        self.action_save.setToolTip(_translate("MainWindow", "保存(S)"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_save_as.setText(_translate("MainWindow", "另存为(&A)…"))
        self.action_print.setText(_translate("MainWindow", "打印(&P)…"))
        self.action_print.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_print_preview.setText(_translate("MainWindow", "打印预览(&V)"))
        self.action_print_set.setText(_translate("MainWindow", "打印设置(&R)…"))
        self.action_quit.setText(_translate("MainWindow", "退出(&X)"))
        self.action_revoke.setText(_translate("MainWindow", "撤销(&U)"))
        self.action_revoke.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_recovery.setText(_translate("MainWindow", "恢复(&R)"))
        self.action_recovery.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_shear.setText(_translate("MainWindow", "剪切(&T)"))
        self.action_shear.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.action_copy.setText(_translate("MainWindow", "复制(&C)"))
        self.action_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_paste.setText(_translate("MainWindow", "粘贴(&P)"))
        self.action_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_delete.setText(_translate("MainWindow", "删除(&D)"))
        self.action_delete.setShortcut(_translate("MainWindow", "Del"))
        self.action_toolbar.setText(_translate("MainWindow", "工具栏(&T)"))
        self.action_statubar.setText(_translate("MainWindow", "状态栏(&S)"))
        self.action_toolbox.setText(_translate("MainWindow", "工具箱(&B)"))
        self.action_toolbox.setShortcut(_translate("MainWindow", "F2"))
        self.action_attribute_panel.setText(_translate("MainWindow", "属性面板(&P)"))
        self.action_attribute_panel.setShortcut(_translate("MainWindow", "F3"))
        self.action_line.setText(_translate("MainWindow", "直线(&L)"))
        self.action_broken_line.setText(_translate("MainWindow", "折线(&P)"))
        self.action_rect.setText(_translate("MainWindow", "矩形(&R)"))
        self.action_ellipse.setText(_translate("MainWindow", "椭圆(&E)"))
        self.action_curve.setText(_translate("MainWindow", "曲线(&C)"))
        self.action_polygon.setText(_translate("MainWindow", "多边形(&G)"))
        self.action_select.setText(_translate("MainWindow", "选取(&S)"))
        self.action_adjust.setText(_translate("MainWindow", "调整(&A)"))
        self.action_scale.setText(_translate("MainWindow", "缩放(&S)"))
        self.action_rotate.setText(_translate("MainWindow", "旋转(&R)"))
        self.action_90_clockwise.setText(_translate("MainWindow", "顺时针旋转90度(&W)"))
        self.action_90_clockwise.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.action_90_anti_clockwise.setText(_translate("MainWindow", "逆时针旋转90度(&C)"))
        self.action_90_anti_clockwise.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.action_180rotate.setText(_translate("MainWindow", "旋转180度(&R)"))
        self.action_horizontal_flip.setText(_translate("MainWindow", "水平翻转(&H)"))
        self.action_horizontal_flip.setShortcut(_translate("MainWindow", "Ctrl+Shift+Right"))
        self.action_vertical_flip.setText(_translate("MainWindow", "垂直翻转(&V)"))
        self.action_vertical_flip.setShortcut(_translate("MainWindow", "Ctrl+Shift+Left"))
        self.action_ink_bottle.setText(_translate("MainWindow", "墨水瓶(&I)"))
        self.action_paint_pot.setText(_translate("MainWindow", "油漆桶(&B)"))
        self.action_straw.setText(_translate("MainWindow", "吸管(&E)"))
        self.action_depict_color.setText(_translate("MainWindow", "描绘颜色(&P)…"))
        self.action_fill_color.setText(_translate("MainWindow", "填充颜色(&F)…"))
        self.action_default_color.setText(_translate("MainWindow", "默认颜色(&D)"))
        self.action_no_color.setText(_translate("MainWindow", "没有颜色(&N)"))
        self.action_move_top.setText(_translate("MainWindow", "移到最上(&T)"))
        self.action_move_top.setShortcut(_translate("MainWindow", "Ctrl+Shift+Up"))
        self.action_move_up.setText(_translate("MainWindow", "上移一层(&U)"))
        self.action_move_up.setShortcut(_translate("MainWindow", "Ctrl+Up"))
        self.action_move_down.setText(_translate("MainWindow", "下移一层(&D)"))
        self.action_move_down.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.action_move_bottom.setText(_translate("MainWindow", "移到最下(&B)"))
        self.action_move_bottom.setShortcut(_translate("MainWindow", "Ctrl+Shift+Down"))
        self.action_use.setText(_translate("MainWindow", "使用"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_out_image.setText(_translate("MainWindow", "导出"))

from drawwidget import DrawWidget
from icon import *
