# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 26))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_E = QtWidgets.QMenu(self.menubar)
        self.menu_E.setObjectName("menu_E")
        self.menu_P = QtWidgets.QMenu(self.menubar)
        self.menu_P.setObjectName("menu_P")
        self.menu_C = QtWidgets.QMenu(self.menubar)
        self.menu_C.setObjectName("menu_C")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_T = QtWidgets.QMenu(self.menu)
        self.menu_T.setObjectName("menu_T")
        self.menu_C_2 = QtWidgets.QMenu(self.menu)
        self.menu_C_2.setObjectName("menu_C_2")
        self.menu_O = QtWidgets.QMenu(self.menu)
        self.menu_O.setObjectName("menu_O")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar_2.sizePolicy().hasHeightForWidth())
        self.toolBar_2.setSizePolicy(sizePolicy)
        self.toolBar_2.setOrientation(QtCore.Qt.Vertical)
        self.toolBar_2.setIconSize(QtCore.QSize(30, 30))
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_3)
        MainWindow.insertToolBarBreak(self.toolBar_3)
        self.action_9 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images/arrow_m.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_9.setIcon(icon)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/images/adjust.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_10.setIcon(icon1)
        self.action_10.setObjectName("action_10")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/images/selmov.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_15.setIcon(icon2)
        self.action_15.setObjectName("action_15")
        self.action_16 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/image/images/rotate.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_16.setIcon(icon3)
        self.action_16.setObjectName("action_16")
        self.action_N = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/images/XinJian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_N.setIcon(icon4)
        self.action_N.setObjectName("action_N")
        self.action_C = QtWidgets.QAction(MainWindow)
        self.action_C.setObjectName("action_C")
        self.action_A = QtWidgets.QAction(MainWindow)
        self.action_A.setObjectName("action_A")
        self.action_P = QtWidgets.QAction(MainWindow)
        self.action_P.setObjectName("action_P")
        self.action_V = QtWidgets.QAction(MainWindow)
        self.action_V.setObjectName("action_V")
        self.action_R_2 = QtWidgets.QAction(MainWindow)
        self.action_R_2.setObjectName("action_R_2")
        self.action_X = QtWidgets.QAction(MainWindow)
        self.action_X.setObjectName("action_X")
        self.action_U = QtWidgets.QAction(MainWindow)
        self.action_U.setObjectName("action_U")
        self.action_R_3 = QtWidgets.QAction(MainWindow)
        self.action_R_3.setObjectName("action_R_3")
        self.action_T = QtWidgets.QAction(MainWindow)
        self.action_T.setObjectName("action_T")
        self.action_C_2 = QtWidgets.QAction(MainWindow)
        self.action_C_2.setObjectName("action_C_2")
        self.action_P_2 = QtWidgets.QAction(MainWindow)
        self.action_P_2.setObjectName("action_P_2")
        self.action_D = QtWidgets.QAction(MainWindow)
        self.action_D.setObjectName("action_D")
        self.action_P_3 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/image/images/zhexian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_P_3.setIcon(icon5)
        self.action_P_3.setObjectName("action_P_3")
        self.action_R_4 = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/image/images/rect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_R_4.setIcon(icon6)
        self.action_R_4.setObjectName("action_R_4")
        self.action_E = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/image/images/ellipse.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_E.setIcon(icon7)
        self.action_E.setObjectName("action_E")
        self.action_C_3 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/image/images/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_C_3.setIcon(icon8)
        self.action_C_3.setObjectName("action_C_3")
        self.action_G = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/image/images/polygon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_G.setIcon(icon9)
        self.action_G.setObjectName("action_G")
        self.action_S = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/image/images/11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_S.setIcon(icon10)
        self.action_S.setObjectName("action_S")
        self.action_R_5 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/image/images/12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_R_5.setIcon(icon11)
        self.action_R_5.setObjectName("action_R_5")
        self.action_90_W = QtWidgets.QAction(MainWindow)
        self.action_90_W.setObjectName("action_90_W")
        self.action_90_C = QtWidgets.QAction(MainWindow)
        self.action_90_C.setObjectName("action_90_C")
        self.action_180_R = QtWidgets.QAction(MainWindow)
        self.action_180_R.setObjectName("action_180_R")
        self.action_H = QtWidgets.QAction(MainWindow)
        self.action_H.setObjectName("action_H")
        self.action_V_2 = QtWidgets.QAction(MainWindow)
        self.action_V_2.setObjectName("action_V_2")
        self.action_I = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/image/images/inkbottle.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_I.setIcon(icon12)
        self.action_I.setObjectName("action_I")
        self.action_B = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/image/images/cursor1.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_B.setIcon(icon13)
        self.action_B.setObjectName("action_B")
        self.action_E_2 = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/image/images/eyedropp.cur"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_E_2.setIcon(icon14)
        self.action_E_2.setObjectName("action_E_2")
        self.action_P_4 = QtWidgets.QAction(MainWindow)
        self.action_P_4.setObjectName("action_P_4")
        self.action_F = QtWidgets.QAction(MainWindow)
        self.action_F.setObjectName("action_F")
        self.action_D_2 = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/image/images/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_D_2.setIcon(icon15)
        self.action_D_2.setObjectName("action_D_2")
        self.action_N_2 = QtWidgets.QAction(MainWindow)
        self.action_N_2.setObjectName("action_N_2")
        self.action_T_2 = QtWidgets.QAction(MainWindow)
        self.action_T_2.setObjectName("action_T_2")
        self.action_U_2 = QtWidgets.QAction(MainWindow)
        self.action_U_2.setObjectName("action_U_2")
        self.action_D_3 = QtWidgets.QAction(MainWindow)
        self.action_D_3.setObjectName("action_D_3")
        self.action_B_2 = QtWidgets.QAction(MainWindow)
        self.action_B_2.setObjectName("action_B_2")
        self.action_O_2 = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/image/images/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_O_2.setIcon(icon16)
        self.action_O_2.setObjectName("action_O_2")
        self.action_S_2 = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/image/images/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_S_2.setIcon(icon17)
        self.action_S_2.setObjectName("action_S_2")
        self.action_T_3 = QtWidgets.QAction(MainWindow)
        self.action_T_3.setObjectName("action_T_3")
        self.action_S_3 = QtWidgets.QAction(MainWindow)
        self.action_S_3.setObjectName("action_S_3")
        self.action_B_3 = QtWidgets.QAction(MainWindow)
        self.action_B_3.setObjectName("action_B_3")
        self.action_P_5 = QtWidgets.QAction(MainWindow)
        self.action_P_5.setObjectName("action_P_5")
        self.action_L = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/image/images/line.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_L.setIcon(icon18)
        self.action_L.setObjectName("action_L")
        self.menu_F.addAction(self.action_N)
        self.menu_F.addAction(self.action_O_2)
        self.menu_F.addAction(self.action_C)
        self.menu_F.addAction(self.action_S_2)
        self.menu_F.addAction(self.action_A)
        self.menu_F.addAction(self.action_P)
        self.menu_F.addAction(self.action_V)
        self.menu_F.addAction(self.action_R_2)
        self.menu_F.addAction(self.action_X)
        self.menu_E.addAction(self.action_U)
        self.menu_E.addAction(self.action_R_3)
        self.menu_E.addAction(self.action_T)
        self.menu_E.addAction(self.action_C_2)
        self.menu_E.addAction(self.action_P_2)
        self.menu_E.addAction(self.action_D)
        self.menu_P.addAction(self.action_T_3)
        self.menu_P.addAction(self.action_S_3)
        self.menu_P.addAction(self.action_B_3)
        self.menu_P.addAction(self.action_P_5)
        self.menu_C.addAction(self.action_P_3)
        self.menu_C.addAction(self.action_R_4)
        self.menu_C.addAction(self.action_E)
        self.menu_C.addAction(self.action_C_3)
        self.menu_C.addAction(self.action_G)
        self.menu_C.addAction(self.action_L)
        self.menu_T.addAction(self.action_S)
        self.menu_T.addAction(self.action_R_5)
        self.menu_T.addAction(self.action_90_W)
        self.menu_T.addAction(self.action_90_C)
        self.menu_T.addAction(self.action_180_R)
        self.menu_T.addAction(self.action_H)
        self.menu_T.addAction(self.action_V_2)
        self.menu_C_2.addAction(self.action_I)
        self.menu_C_2.addAction(self.action_B)
        self.menu_C_2.addAction(self.action_E_2)
        self.menu_C_2.addAction(self.action_P_4)
        self.menu_C_2.addAction(self.action_F)
        self.menu_C_2.addAction(self.action_D_2)
        self.menu_C_2.addAction(self.action_N_2)
        self.menu_O.addAction(self.action_T_2)
        self.menu_O.addAction(self.action_U_2)
        self.menu_O.addAction(self.action_D_3)
        self.menu_O.addAction(self.action_B_2)
        self.menu.addAction(self.action_9)
        self.menu.addAction(self.action_10)
        self.menu.addAction(self.menu_T.menuAction())
        self.menu.addAction(self.menu_C_2.menuAction())
        self.menu.addAction(self.menu_O.menuAction())
        self.menu_2.addAction(self.action_13)
        self.menu_2.addAction(self.action_14)
        self.menu_3.addAction(self.action_15)
        self.menu_3.addAction(self.action_16)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_P.menuAction())
        self.menubar.addAction(self.menu_C.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.action_N)
        self.toolBar.addAction(self.action_O_2)
        self.toolBar.addAction(self.action_S_2)
        self.toolBar_2.addAction(self.action_9)
        self.toolBar_2.addAction(self.action_L)
        self.toolBar_2.addAction(self.action_R_4)
        self.toolBar_2.addAction(self.action_C_3)
        self.toolBar_2.addAction(self.action_I)
        self.toolBar_2.addAction(self.action_E_2)
        self.toolBar_2.addAction(self.action_D_2)
        self.toolBar_2.addAction(self.action_S)
        self.toolBar_3.addAction(self.action_10)
        self.toolBar_3.addAction(self.action_P_3)
        self.toolBar_3.addAction(self.action_E)
        self.toolBar_3.addAction(self.action_G)
        self.toolBar_3.addAction(self.action_B)
        self.toolBar_3.addAction(self.action_R_5)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_E.setTitle(_translate("MainWindow", "编辑(E)"))
        self.menu_P.setTitle(_translate("MainWindow", "查看(V)"))
        self.menu_C.setTitle(_translate("MainWindow", "图形(I)"))
        self.menu.setTitle(_translate("MainWindow", "修改(M)"))
        self.menu_T.setTitle(_translate("MainWindow", "转换(&T)"))
        self.menu_C_2.setTitle(_translate("MainWindow", "颜色(C)"))
        self.menu_O.setTitle(_translate("MainWindow", "排序(&O)"))
        self.menu_2.setTitle(_translate("MainWindow", "窗口(W)"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助(H)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.action_9.setText(_translate("MainWindow", "选取(&S)"))
        self.action_10.setText(_translate("MainWindow", "调整(&A)"))
        self.action_13.setText(_translate("MainWindow", "放大"))
        self.action_14.setText(_translate("MainWindow", "缩小"))
        self.action_15.setText(_translate("MainWindow", "移动"))
        self.action_16.setText(_translate("MainWindow", "旋转"))
        self.action_N.setText(_translate("MainWindow", "新建(&N)"))
        self.action_N.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_C.setText(_translate("MainWindow", "关闭(&C)"))
        self.action_A.setText(_translate("MainWindow", "另存为(&A)"))
        self.action_P.setText(_translate("MainWindow", "打印(&P)"))
        self.action_P.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_V.setText(_translate("MainWindow", "打印预览(&V)"))
        self.action_R_2.setText(_translate("MainWindow", "打印设置(&R)"))
        self.action_X.setText(_translate("MainWindow", "退出(&X)"))
        self.action_U.setText(_translate("MainWindow", "撤销(&U)"))
        self.action_U.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_R_3.setText(_translate("MainWindow", "恢复(&R)"))
        self.action_R_3.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_T.setText(_translate("MainWindow", "剪切(&T)"))
        self.action_T.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.action_C_2.setText(_translate("MainWindow", "复制(&C)"))
        self.action_C_2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_P_2.setText(_translate("MainWindow", "粘贴(&P)"))
        self.action_P_2.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_D.setText(_translate("MainWindow", "删除(&D)"))
        self.action_D.setShortcut(_translate("MainWindow", "Del"))
        self.action_P_3.setText(_translate("MainWindow", "折线(&P)"))
        self.action_R_4.setText(_translate("MainWindow", "矩形(&R)"))
        self.action_E.setText(_translate("MainWindow", "椭圆(&E)"))
        self.action_C_3.setText(_translate("MainWindow", "曲线(&C)"))
        self.action_G.setText(_translate("MainWindow", "多边形(&G)"))
        self.action_S.setText(_translate("MainWindow", "缩放(&S)"))
        self.action_R_5.setText(_translate("MainWindow", "旋转(&R)"))
        self.action_90_W.setText(_translate("MainWindow", "顺时针旋转90度(&W)"))
        self.action_90_W.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.action_90_C.setText(_translate("MainWindow", "逆时针旋转90度(&C)"))
        self.action_90_C.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.action_180_R.setText(_translate("MainWindow", "旋转180度(&R)"))
        self.action_H.setText(_translate("MainWindow", "水平翻转(&H)"))
        self.action_H.setShortcut(_translate("MainWindow", "Ctrl+Shift+Right"))
        self.action_V_2.setText(_translate("MainWindow", "垂直翻转(&V)"))
        self.action_V_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+Left"))
        self.action_I.setText(_translate("MainWindow", "墨水瓶(&I)"))
        self.action_B.setText(_translate("MainWindow", "油漆桶(&B)"))
        self.action_E_2.setText(_translate("MainWindow", "吸管(&E)"))
        self.action_P_4.setText(_translate("MainWindow", "描绘颜色(&P)"))
        self.action_F.setText(_translate("MainWindow", "填充颜色(&F)"))
        self.action_D_2.setText(_translate("MainWindow", "默认颜色(&D)"))
        self.action_N_2.setText(_translate("MainWindow", "没有颜色(&N)"))
        self.action_T_2.setText(_translate("MainWindow", "移到最上(&T)"))
        self.action_T_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+Up"))
        self.action_U_2.setText(_translate("MainWindow", "上移一层(&U)"))
        self.action_U_2.setShortcut(_translate("MainWindow", "Ctrl+Up"))
        self.action_D_3.setText(_translate("MainWindow", "下移一层(&D)"))
        self.action_D_3.setShortcut(_translate("MainWindow", "Ctrl+Down"))
        self.action_B_2.setText(_translate("MainWindow", "移到最下(&B)"))
        self.action_B_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+Down"))
        self.action_O_2.setText(_translate("MainWindow", "打开(&O)"))
        self.action_O_2.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_S_2.setText(_translate("MainWindow", "保存(&S)"))
        self.action_S_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_T_3.setText(_translate("MainWindow", "工具栏(&T)"))
        self.action_S_3.setText(_translate("MainWindow", "状态栏(&S)"))
        self.action_B_3.setText(_translate("MainWindow", "工具箱(&B)"))
        self.action_B_3.setShortcut(_translate("MainWindow", "F2"))
        self.action_P_5.setText(_translate("MainWindow", "属性面板(&P)"))
        self.action_P_5.setShortcut(_translate("MainWindow", "F3"))
        self.action_L.setText(_translate("MainWindow", "直线(&L)"))

import resources_rc
